# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-WWW-Mechanize
version:      1.06
version_from: Mechanize.pm
installdirs:  site
requires:
    Carp::Assert::More:            0
    HTTP::Server::Simple:          0.07
    Test::LongString:              0.07
    Test::More:                    0
    URI::file:                     0
    WWW::Mechanize:                1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
